# Lopuksi

Tässä tutkielmassa on esitetty pääpiirteittäin hiukkassuodin- ja hiukkassiloitinalgoritmien teoria Bayesilaisessa tilastotieteellisessä viitekehyksessä. Lisäksi on käyty läpi uudelleenotantaa efektiivisen otoskoon perusteella hyödyntävä SIR-suodinalgoritmi sekä käsitelty algoritmin varianssin estimointia. Tutkielmassa on myös esitetty SIR-algoritmin parametrien valintaan, suorituskykyyn sekä konvergenssiin liittyviä tuloksia.

Tutkielmassa on esitetty myös WB-sisätilapaikannusalgoritmi, joka toteuttaa SIR-algoritmin, estimoi jakaumaestimaatin varianssin ja hyödyntää sisätilapaikannuksen karttasovitusalgoritmia. Tutkielmassa on lopuksi tarkasteltu miten eri suunnitteluparametrien valinnat vaikuttavat algoritmin suorituskykyyn kattavan, todelliseen ongelmaan ja dataan perustuvan paikannuskokeen avulla.

Koe-esimerkin perusteella näyttää siltä, että tutkielmassa käsitelty ALVar-varianssiestimaatti heijastaa hyvin jakaumaestimaatin todellista varianssia. Sitä voisi edelleen hyödyntää esimerkiksi adaptiivisen viipeen siloittimen toteuttamisessa. Varianssiestimaattia voitaisiin käyttää myös WB-sisätilapaikannusalgoritmin dynaamisen mallin kohinaparametrin $q$ säätämisessä niin, että kohinaa lisättäisiin tai vähennettäisiin varianssiestimaatin perusteella. Tämä voitaisiin toteuttaa esimerkiksi käyttämällä lähtökohtaisesti pienempää $q$-arvoa ja lisäämällä siihen keskihajonnan estimaatti, jota on painotettu suunnitteluparametrilla $\alpha$, ts. ennen dynaamisen mallin sovittamista säädettäisiin kohinaparametri $q_k = q+\alpha\sqrt{\hat{\sigma}^2_{k-1}}$. Vastaavaa mallia ovat käyttäneet esimerkiksi Xu ja Li (2006) [@Xu-2006].

Varianssiestimaattia voisi lisäksi käyttää hiukkasmäärän $N$ adaptiiviseen valintaan: matala varianssi vähentäisi estimoinnissa käytettävien hiukkasten määrää. Tällaista varianssiin perustuvaa hiukkasmäärän muuttamista ehdottavat muun muassa Lee ja Whiteley (2018) [@Lee-2018]. 

Hiukkasten määrää voisi säätää myös arvioimalla hiukkassuotimen konvergenssia esimerkiksi Elviran &al. (2017) esittämän menetelmän avulla [@Elvira-2017]. Hiukkasten määrän dynaamisella valinnalla saavutettaisiin todennäköisesti merkittäviä laskennallisia säästöjä, koska WB-sisätilapaikannusalgoritmia sovelletaan yksittäisessä kohteessa samanaikaisesti useiden satojen AT-2-tägien paikantamiseen.

Algoritmin suorituskykyä voitaisiin mahdollisesti myös parantaa käyttämällä RSSI-kynnysarvon sijaan tai ohella esimerkiksi menetelmää, jossa datasta poistettaisiin kullakin aika-askeleella ne kulmahavainnot, jotka poikkeavat kulmahavaintojen suuntakonsensuksesta (kts. esim. Boquet &al. (2024) [@Boquet-2024]). Jättämällä osa havainnoista uskottavuusfunktioiden ulkopuolelle nopeuttaisi algoritmin laskentaa, mutta saattaisi parantaa myös algoritmin tarkkuutta.

Liitteenä olevista polkukuvista voidaan havaita, että nykyinen algoritmi jää välillä jälkeen itse tagin sijainnista. Tätä ongelmaa voitaisiin mahdollisesti lieventää käyttämällä mm. Yi Chenging &al. artikkelissa "Improved Particle Filter Algorithm for Multi-Target Detection and Tracking" (2024) [@Cheng-2024] esittämää menetelmää, jossa partikkelit jaetaan ns. seurantahiukkasiin sekä etsintähiukkasiin, joista ainoastaan edellisiä käytetään sijaintiestimaatin luomisessa ja jälkimmäisten annetaan liikkua suuremmilla kohina-arvoilla. Näin mahdollistetaan satunnaiskulkumallilla laajempi signaaliavaruuden tutkinta ja nopeampi ongelmatilanteista toipuminen ilman, että sijaintiestimaatit kärsivät liikemalliin lisätystä kohinasta.

Jälkeenjäämisongelmaa voitaisiin lieventää myös käyttämällä ekskluusiopolygonien ohella ns. pehmeitä rajoitteita (kts. esim. Liu &al. (2019) [@Liu-2019]), jolloin ekskluusiopolygonien ympärille luotaisiin rajoitevyöhyke, jolle osuvat hiukkaset saisivat rangaistuksen riippuen siitä, kuinka lähellä itse ekskluusiopolygonin reunaa ne ovat. Rangaistusarvon luomisessa voitaisiin käyttää esimerkiksi eksponentiaalista tai kvadraattista hajoamista.

Algoritmin optimaalisia suunnitteluparametreja etsivän kokeen voisi myös toteuttaa käyttäen geneettisiä algoritmeja, Bayesilaista optimointia tai sensitiivisyysanalyysia, olettaen, että parametrit ovat toisistaan riippumattomia.

Algoritmia ja järjestelmää voitaisiin edelleen parantaa käyttämällä tagia, jonka kiihtyvyysmittarin tuottama data olisi AT-2-tagia luotettavampaa. Kiihtyvyyssataa voitaisiin hyödyntää esimerkiksi informatiivisen liikemallin luomisessa.